import dotenv from "dotenv";
import connectDB from "./db.js";
dotenv.config();
connectDB();
import User from "./models/user.model.js";
import Tag from "./models/tags.model.js";
import Comment from "./models/comments.model.js";
import Post from "./models/post.model.js";
import Token from "./models/token.model.js";
import Otp from "./models/otp.model.js";
import Newsletter from "./models/newsletter.model.js";
import Contact from "./models/contact.model.js";
export { connectDB, User, Tag, Comment, Post, Token, Otp, Newsletter, Contact };
